### ISSUE TITLE
Consider adding $N which would help with documentation

### ISSUE THREAD

**Issue by jbfaden** [uri-templates-time/uri-templates#6]
I'd like for us to consider allowing $N to be the equivalent of $(subsec,places=9).  Note Linux's date command uses it, so it follows that precedent, and it gives a one-letter name for the place in code.  For example, I have a 7-element array I use to pass around times, and I can name each place with a one-character label Y, h, m, H, M, S, but not the last one, which I call nanos.  I think it would be useful to have this, and it would be a trivial extension of the spec.

**Comment by jbfaden** [comment]
`
    /**
     * parse the ISO8601 time range, like "1998-01-02/1998-01-17", into
     * start and stop times, returned in a 14 element array of ints.
     * @param stringIn
     * @return the time start and stop [ Y,m,d,H,M,S,nano, Y,m,d,H,M,S,nano ]
     * @throws ParseException 
     */
`

**Comment by rweigel** [comment]
I agree with this addition in principle. For clarity, would you describe a unit test that would go into the formatting.json file? I don't see a `subsec` example there and use this file more than the actual spect to understand the notation.

**Comment by jbfaden** [comment]
I was just looking at those tests.  I can put one in for subsec...  Also note I added "id" which is to be a unique identifier for each test.

**Comment by jbfaden** [comment]
I noticed that we do have $N reserved for future use (this use).

**Comment by jbfaden** [comment]
This was done sometime during the last year.
